// <auto-generated />
using EE.HolidayHomes.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EE.HolidayHomes.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250609061748_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EE.HolidayHomes.Core.Entities.HolidayHome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("HolidayHomes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "house1.jpg",
                            LocationId = 1,
                            Name = "The Villa",
                            Price = 120.50m
                        },
                        new
                        {
                            Id = 2,
                            Image = "house2.jpg",
                            LocationId = 2,
                            Name = "The Cottage",
                            Price = 250.55m
                        },
                        new
                        {
                            Id = 3,
                            Image = "house3.jpg",
                            LocationId = 3,
                            Name = "The farmhouse",
                            Price = 350.50m
                        },
                        new
                        {
                            Id = 4,
                            Image = "house4.jpg",
                            LocationId = 4,
                            Name = "The seaside house",
                            Price = 350.55m
                        });
                });

            modelBuilder.Entity("EE.HolidayHomes.Core.Entities.HomeProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomeProperties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rural"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Seaside"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Luxury"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Budget"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("EE.HolidayHomes.Core.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lapscheure"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Izegem"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Blankenberge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sint-Pieterskapelle"
                        });
                });

            modelBuilder.Entity("EE.HolidayHomes.Core.Entities.HolidayHome", b =>
                {
                    b.HasOne("EE.HolidayHomes.Core.Entities.Location", "Location")
                        .WithMany("HolidayHomes")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EE.HolidayHomes.Core.Entities.Location", b =>
                {
                    b.Navigation("HolidayHomes");
                });
#pragma warning restore 612, 618
        }
    }
}
